# ==========================================
# ALERT & EMAIL SYSTEM — COMPONENT MODULE
# ==========================================

import smtplib
import numpy as np
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart


# ==========================================
# DYNAMIC ALERT LEVEL EVALUATION
# ==========================================
def evaluate_alert(rul_value: float, all_rul_values):
    """
    Dynamic alert based on RUL distribution
    """

    p75 = np.percentile(all_rul_values, 75)
    p50 = np.percentile(all_rul_values, 50)
    p25 = np.percentile(all_rul_values, 25)

    if rul_value >= p75:
        return "LOW", "Normal operation — continue monitoring"

    elif p50 <= rul_value < p75:
        return "MEDIUM", "Schedule preventive maintenance"

    elif p25 <= rul_value < p50:
        return "HIGH", "Maintenance required soon"

    else:
        return "CRITICAL", "Immediate shutdown / service required"


# ==========================================
# EMAIL ALERT SENDER
# ==========================================
def send_email_alert(machine, rul, level, action):

    SMTP_SERVER = "smtp.gmail.com"
    SMTP_PORT = 587

    SENDER_EMAIL = "2200080196.aids@gmail.com"
    SENDER_PASSWORD = "tbso yfis iree jgjy"
    RECEIVER_EMAIL = "appanavaishnavi26@gmail.com"

    subject = f"🚨 Predictive Maintenance Alert — {machine}"

    body = f"""
Machine Alert Triggered

Machine: {machine}
Predicted RUL: {rul:.2f} hours
Alert Level: {level}

Recommended Action:
{action}

Generated by AI Maintenance Dashboard
"""

    try:
        msg = MIMEMultipart()
        msg["From"] = SENDER_EMAIL
        msg["To"] = RECEIVER_EMAIL
        msg["Subject"] = subject
        msg.attach(MIMEText(body, "plain"))

        server = smtplib.SMTP(SMTP_SERVER, SMTP_PORT)
        server.starttls()
        server.login(SENDER_EMAIL, SENDER_PASSWORD)
        server.send_message(msg)
        server.quit()

        return True

    except Exception as e:
        print("Email send error:", e)
        return False